#!/usr/bin/env python3
"""Generate native/wyatt_js_embed.h from src/*.js.

Usage: python3 scripts/gen_native_embed.py

Reads Y@ JS modules from src/, strips ESM import/export lines,
writes readable C string literals into native/wyatt_js_embed.h.
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
OUT = os.path.join(ROOT, "native", "wyatt_js_embed.h")

# Modules in load order (dependencies first)
MODULES = [
    ("reactive.js",        "js_reactive_src"),
    ("prolog-engine.js",   "js_prolog_engine_src"),
    ("parser.js",          "js_parser_src"),
    ("reactive-prolog.js", "js_reactive_prolog_src"),
    ("qjson.js",           "js_qjson_src"),
    ("persist.js",         "js_persist_src"),
    ("fossilize.js",       "js_fossilize_src"),
]


def strip_esm(source):
    lines = source.split("\n")
    out = []
    for line in lines:
        s = line.strip()
        if s.startswith("import "):
            continue
        if s.startswith("export "):
            continue
        out.append(line)
    while out and out[-1].strip() == "":
        out.pop()
    return "\n".join(out) + "\n"


def to_c_string(source, var_name):
    lines = source.split("\n")
    out = ["static const char %s[] =" % var_name]
    for line in lines:
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append('  "%s\\n"' % escaped)
    out.append(";\n")
    return "\n".join(out)


# Minimal loadString that works in QuickJS global scope
LOADSTRING_JS = """\
function loadString(engine, text) {
  var clauses = parseProgram(text);
  for (var i = 0; i < clauses.length; i++) {
    engine.addClause(clauses[i].head, clauses[i].body);
  }
  return clauses.length;
}
"""


def main():
    header = "/* Auto-generated by scripts/gen_native_embed.py — do not edit.\n"
    header += "   Source: src/ */\n"
    header += "#ifndef WYATT_JS_EMBED_H\n#define WYATT_JS_EMBED_H\n\n"

    for filename, var_name in MODULES:
        path = os.path.join(SRC, filename)
        raw = open(path).read()
        clean = strip_esm(raw)
        header += to_c_string(clean, var_name) + "\n"

    header += to_c_string(LOADSTRING_JS, "js_load_string_src") + "\n"
    header += "#endif\n"

    with open(OUT, "w") as f:
        f.write(header)
    print("wrote %s (%d bytes)" % (OUT, len(header)))


if __name__ == "__main__":
    main()
