#!/usr/bin/env python3
"""Generate native/y8_js_embed.h from src/*.js.

Usage: python3 scripts/gen_native_embed.py

Reads y8 JS modules from src/, strips ESM import/export lines,
writes readable C string literals into native/y8_js_embed.h.
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
VENDOR_QJSON = os.path.join(ROOT, "vendor", "qjson", "src")
OUT = os.path.join(ROOT, "native", "y8_js_embed.h")

# Modules in load order (dependencies first)
# Each entry: (filename, c_var_name, source_dir)
MODULES = [
    ("reactive.js",        "y8_js_reactive",        SRC),
    ("prolog-engine.js",   "y8_js_prolog_engine",   SRC),
    ("parser.js",          "y8_js_parser",           SRC),
    ("reactive-prolog.js", "y8_js_reactive_prolog",  SRC),
    ("qjson.js",           "y8_js_qjson",            VENDOR_QJSON),
    ("persist.js",         "y8_js_persist",           SRC),
    ("fossilize.js",       "y8_js_fossilize",         SRC),
]


def strip_esm(source):
    lines = source.split("\n")
    out = []
    for line in lines:
        s = line.strip()
        if s.startswith("import "):
            continue
        if s.startswith("export "):
            continue
        out.append(line)
    while out and out[-1].strip() == "":
        out.pop()
    return "\n".join(out) + "\n"


def to_c_string(source, var_name):
    lines = source.split("\n")
    out = ["static const char %s[] =" % var_name]
    for line in lines:
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append('  "%s\\n"' % escaped)
    out.append(";\n")
    return "\n".join(out)


# Minimal loadString that works in QuickJS global scope
LOADSTRING_JS = """\
function loadString(engine, text) {
  var clauses = parseProgram(text);
  for (var i = 0; i < clauses.length; i++) {
    engine.addClause(clauses[i].head, clauses[i].body);
  }
  return clauses.length;
}
"""


def main():
    header = "/* Auto-generated by scripts/gen_native_embed.py — do not edit.\n"
    header += "   Source: src/ */\n"
    header += "#ifndef Y8_JS_EMBED_H\n#define Y8_JS_EMBED_H\n\n"

    for filename, var_name, src_dir in MODULES:
        path = os.path.join(src_dir, filename)
        raw = open(path).read()
        clean = strip_esm(raw)
        header += to_c_string(clean, var_name) + "\n"

    header += to_c_string(LOADSTRING_JS, "y8_js_load_string") + "\n"
    header += "#endif\n"

    with open(OUT, "w") as f:
        f.write(header)
    print("wrote %s (%d bytes)" % (OUT, len(header)))


if __name__ == "__main__":
    main()
